import { Heading, Text, VStack } from "@chakra-ui/react";
import Head from "next/head";

export default function Post({ post }: any) {
  return (
    <>
      <Head>
        <meta
          name="description"
          content="Search homes for sale, new construction homes, apartments, and houses for rent. See property values. Shop mortgages."
        />
        <meta property="og:URL" content="https://www.realtor.com" />
        <meta
          property="og:title"
          content="realtor.com® | Homes for Sale, Apartments &amp; Houses for Rent"
        />
        <meta
          property="og:description"
          content="Search homes for sale, new construction homes, apartments, and houses for rent. See property values. Shop mortgages."
        />
        <title>Advanced nextjs -Learning</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />

        <meta property="og:type" content="website" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <VStack maxW="container.lg" mx="auto" p="2em 4em">
        <Heading mb="1em" w="full" textAlign="left">
          Blog Post
        </Heading>
        <Text m="5" mt="0">
          Lorem ipsum dolor sit amet consectetur adipisicing elit. Maxime ipsum
          odit soluta facere voluptatem doloremque dolorem, veniam nihil tempora
          itaque similique libero! Doloremque dicta est corrupti eligendi et
          quae blanditiis.
        </Text>
        <Text m="5" mt="0">
          Lorem ipsum dolor sit amet consectetur adipisicing elit. Maxime ipsum
          odit soluta facere voluptatem doloremque dolorem, veniam nihil tempora
          itaque similique libero! Doloremque dicta est corrupti eligendi et
          quae blanditiis.
        </Text>
        <Text m="5" mt="0">
          Lorem ipsum dolor sit amet consectetur adipisicing elit. Maxime ipsum
          odit soluta facere voluptatem doloremque dolorem, veniam nihil tempora
          itaque similique libero! Doloremque dicta est corrupti eligendi et
          quae blanditiis.
        </Text>
        <Text m="5" mt="0">
          Lorem ipsum dolor sit amet consectetur adipisicing elit. Maxime ipsum
          odit soluta facere voluptatem doloremque dolorem, veniam nihil tempora
          itaque similique libero! Doloremque dicta est corrupti eligendi et
          quae blanditiis.
        </Text>
        <Text m="5" mt="0">
          Lorem ipsum dolor sit amet consectetur adipisicing elit. Maxime ipsum
          odit soluta facere voluptatem doloremque dolorem, veniam nihil tempora
          itaque similique libero! Doloremque dicta est corrupti eligendi et
          quae blanditiis.
        </Text>
        <Text m="5" mt="0">
          Lorem ipsum dolor sit amet consectetur adipisicing elit. Maxime ipsum
          odit soluta facere voluptatem doloremque dolorem, veniam nihil tempora
          itaque similique libero! Doloremque dicta est corrupti eligendi et
          quae blanditiis.
        </Text>
      </VStack>
    </>
  );
}

// Generates `/posts/1` and `/posts/2`
export async function getStaticPaths() {
  return {
    paths: [{ params: { id: "1" } }, { params: { id: "2" } }],
    fallback: false, // can also be true or 'blocking'
  };
}

// `getStaticPaths` requires using `getStaticProps`
export async function getStaticProps(context: any) {
  console.log(context);
  return {
    // Passed to the page component as props
    props: { post: {} },
  };
}
